# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zoAmTKnnR3qRlJPt2UQaFqM6bbvUOWqE
"""

import streamlit as st
import os

# Supongamos que la imagen "valorant.jpg" está en el directorio /content/
image_path = '/content/valorant.jpg'

# Código CSS para establecer la imagen como fondo
st.markdown(
    f"""
    <style>
    body {{
        background-image: url('{image_path}');
        background-size: cover;
        background-position: center;
        height: 100vh;
    }}
    </style>
    """,
    unsafe_allow_html=True
)

# Continuar con el resto de tu aplicación Streamlit
st.title("Mi aplicación con fondo")
st.write("¡Hola! Esto es un ejemplo de cómo establecer una imagen JPG como fondo.")